version: 2

jobs:
  build-job:
    working_directory: ~/collage-gesture-detector

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

    steps:
      - checkout

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job